### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/airtable.do#1]
- [ ] Support OAuth
- [ ] Proxy Base Metadata
- [ ] Generate JSON Export for Table
- [ ] Generate JSON Export for Entire Base
- [ ] Support Webhook Triggers
- [ ] Support Data Enrichment via Webhooks
